# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute the kernel matrix between two sets of data points.
#'
#' @param X1 First set of data points (each row is a data point)
#' @param X2 Second set of data points (each row is a data point)
#' @param kernel_spec R list describing the kernel
#' @return Kernel matrix K
kernelMatrix_cpp <- function(X1, X2, kernel_spec) {
    .Call(`_flexKernel_kernelMatrix_cpp`, X1, X2, kernel_spec)
}

#' Compute the Nystrom approximation of a kernel matrix.
#'
#' @param X Data matrix (each row is a data point)
#' @param num_landmarks Number of landmark points to use
#' @param kernel_spec R list describing the kernel
#' @param regularization Regularization parameter for inverting K_mm
#' @param batch_size Size of mini-batches for k-means
#' @param max_iterations Maximum number of iterations for k-means
#' @param seed Random seed for initialization
#' @return List containing the Nystrom approximation components
computeNystromApproximation_cpp <- function(X, num_landmarks, kernel_spec, regularization = 1e-6, batch_size = 100L, max_iterations = 100L, seed = 42L) {
    .Call(`_flexKernel_computeNystromApproximation_cpp`, X, num_landmarks, kernel_spec, regularization, batch_size, max_iterations, seed)
}

#' Evaluate the kernel function for a single pair of data points.
#'
#' @param x1 First data point (vector)
#' @param x2 Second data point (vector)
#' @param kernel_spec R list describing the kernel
#' @return Kernel value k(x1, x2)
kernelScalar_cpp <- function(x1, x2, kernel_spec) {
    .Call(`_flexKernel_kernelScalar_cpp`, x1, x2, kernel_spec)
}

#' @title Mini-Batch K-Means Clustering
#'
#' @description
#' Performs mini-batch k-means clustering on a given dataset using the k-means++ initialization method.
#' This function is a wrapper around a C++ implementation using RcppEigen for efficiency.
#'
#' @param XR The data matrix with observations in rows (standard R format).
#' @param k The number of clusters.
#' @param batch_size The size of each mini-batch.
#' @param max_epochs The number of full passes over the dataset.
#' @param num_threads The number of OpenMP threads to use for parallel processing.
#'
#' @return A list with the matrix of cluster centers, a vector of cluster assignments (1-based indices), and a status flag.
#'
#' @details
#' This function implements the mini-batch k-means algorithm, which is an approximation of the standard k-means
#' algorithm designed for large datasets. It processes the data in small random subsets (mini-batches) to update
#' the cluster centers incrementally, reducing computational cost and memory usage.
#'
#' The cluster centers are initialized using the k-means++ method, which selects initial centers that are spread out
#' across the dataset to improve convergence.
#'
#' The function uses OpenMP for parallel processing within each mini-batch, leveraging multiple CPU cores to speed up
#' computations.
#'
#' Random selections, including initialization and mini-batch sampling, are performed using R's random number generator
#' to ensure reproducibility with \code{set.seed()}.
#'
#' If any cluster does not receive points during an epoch, it is reinitialized to a random data point to prevent stagnation.
#'
#' @note The input matrix \code{XR} should have observations in rows and features in columns (standard R format).
#' The returned cluster centers have k rows (one per cluster) and the same number of columns as the input data.
#'
#' @examples
#' \dontrun{
#' set.seed(123)
#' X <- matrix(rnorm(1000 * 10), nrow = 1000)  # 1000 observations, 10 features
#' result <- mini_batch_kmeans_rcpp(X, k = 3, batch_size = 100, max_epochs = 10, num_threads = 2)
#' if (result$success) {
#' print(result$means)  # 3 rows (clusters) × 10 columns (features)
#' print(table(result$cluster))  # Distribution of observations across clusters
#' } else {
#' warning("Mini-batch k-means failed.")
#' }
#' }
#'
#' @export
mini_batch_kmeans_rcpp <- function(XR, k, batch_size, max_epochs, num_threads = 1L) {
    .Call(`_flexKernel_mini_batch_kmeans_rcpp`, XR, k, batch_size, max_epochs, num_threads)
}

